### ISSUE TITLE
Granting more permissive license to integrate upstream

### ISSUE THREAD

**Issue by pelletier** [segmentio/asm#84]
Some of the implementations in this repository are drop-in replacement for standard Go library functions. Contributing them back upstream, to [golang/go](https://github.com/golang/go), could benefit the ecosystem as a whole with little drawback to Twilio Segment, as segmentio/asm is already released under the permissive MIT license. However, we did not anticipate the attribution requirement of this license to prevent its adoption in the standard library (example: [`utf8.Valid` CL](https://go-review.googlesource.com/c/go/+/535838/comment/fb1b9e5a_0159192e/)). It is a non-starter to include derivatives of MIT-licensed code in the Go standard library, because it would force all people who distribute Go program binaries to include the license and copyright assignment to Segment.

As a result, would you consider re-licensing the code in this repository to permit its integration into Go without attribution?

For example: [MIT-0](https://opensource.org/license/mit-0/) ("MIT No Attribution License").

Thank you!

**Comment by kevinburkesegment** [comment]
If we relicensed, do you think we could continue to include information about where this code was developed? Ie, a header that says "Code developed at Segment (https://github.com/segmentio/asm)" or similar.

**Comment by achille-roussel** [comment]
Hello Kevin, thanks for getting back to us!

We can add the mention you suggested as a comment in the source, but this cannot be legally binding Go to a software license; it would only be informational.

**Comment by peterdemartini** [comment]
Heyyo! We've submitted an open source review to see if this is something we can do. I will post back here with an update when I hear back.

**Comment by kevinburkesegment** [comment]
> this cannot be legally binding Go to a software license

Oh for sure I just think it would be good to make sure people know where the code was developed.

**Comment by achille-roussel** [comment]
Hello @peterdemartini @kevinburkesegment!

Do you have updates to share on this issue?

**Comment by peterdemartini** [comment]
@achille-roussel no update yet, I will request an update on the internal ticket

**Comment by pelletier** [comment]
Thank you so much everybody! I'll update the upstream CL with the good news.
